config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'about' => 'home#about'

  resources :posts
  resources :comments
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize( user )
    return unless user.present?

    can :manage, Post, user_id: user.id
    can :manage, Comment, user_id: user.id

    can :manage, :all if user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one_attached :file

  validates :title, presence: true
  validates :content, presence: true
  validate :file_size

  def file_size
    errors.add :file, 'too big, max size 2MB' if file.attached? && file.blob.byte_size > 2_000_000
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments

  enum role: %w[admin user]

  def posts?
    posts.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit( :sign_up ) do |user_params|
      user_params.permit( :nickname, :email, :password, :password_confirmation )
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: %i[create update]
  before_action :find_comment, only: %i[destroy update]

  def create
    if comment_params_valid?
      Comment.create( comment_params )
    else
      flash[ :error ] = 'Your comment is blank or something is wrong'
    end

    redirect_to post_path( @post )
  end

  def update
    if @comment.update( comment_params )
      redirect_to post_path( @post )
    else
      render action: 'edit'
    end
  end

  def destroy
    @comment.destroy

    redirect_to post_path( @comment.post )
  end

  private

  def find_post
    @post = Post.find( comment_params[ :post_id ] )
  end

  def find_comment
    @comment = Comment.find( params[ :id ] )
  end

  def comment_params_valid?
    comment_params[ :message ].present? &&
      comment_params[ :post_id ].present? &&
      comment_params[ :user_id ].present?
  end

  def comment_params
    params.require( :comment ).permit( :id, :post_id, :message ).merge( user_id: current_user.id )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @my_posts = Post.where( user_id: current_user.id ) if current_user
    @posts = Post.all.includes( :user ).includes( :comments ).limit( 10 )
  end

  def about; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: %i[show edit update destroy]
  before_action :check_abilities, only: [ :destroy ]

  def new; end

  def create
    @post = Post.new( post_params )
    attach_file if params[ :post ][ :file ].present?

    if post_params_valid?
      @post.save

      redirect_to post_path( @post )
    else
      flash[ :error ] = 'Fields must be filled'
      render action: 'new'
    end
  end

  def show
    @comments = Comment.where( post_id: @post.id )
  end

  def edit; end

  def update
    attach_file if params[ :post ][ :file ].present?

    if @post.update( post_params )
      redirect_to post_path( @post )
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy

    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find( params[ :id ] )
  end

  def post_params_valid?
    post_params[ :title ].present? &&
      post_params[ :content ].present? &&
      post_params[ :user_id ].present?
  end

  def check_abilities
    current_user.admin? || post_belongs_to_current_user?
  end

  def post_belongs_to_current_user?
    current_user.id == @post.user_id
  end

  def attach_file
    @post.file.attach( params[ :post ][ :file ] )
  end

  def post_params
    params.require( :post ).permit( :title, :content ).merge( user_id: current_user.id )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="card border-secondary mb-3" style="width: 35rem;">
  <div class="card-body">
    <p class="card-text"><%= comment.message %></p>
    <p class="card-text">
      <small class="text-muted">
        <%= "Comment created #{comment.created_at.to_date} by " %><%= comment.user.nickname %>
      </small>
    </p>

    <% if can? :manage, comment %>
      <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal">
        Edit comment
      </button>

      <button type="button" class="btn btn-light">
        <%= link_to 'Delete comment', comment_path(comment), method: :delete, data: { confirm: 'A you sure?' } %>
      </button>

      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Edit you comment: <%= comment.message %></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <%= form_for :comment, url: comment_path(comment), method: :put do |f| %>

              <div class="modal-body">
                <%= f.text_field :message %>
                <%= f.hidden_field :post_id, value: @post.id %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= f.submit class: 'btn btn-primary' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_edit_comment.html.erb
<%= form_for( :comment, url: comment_path(comment), method: :put, remote: true ) do |f| %>
  <div class="form-group">
    <%= f.hidden_field :post_id, value: @post.id %>
  </div>
  
  <div class="form-group", id="content">
    <%= f.label :comment %>
    <%= f.text_area :message, class: 'form-control', placeholder: 'Save comment' %>
  </div>

  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<%= form_for :comment, url: comments_path, remote: true do |f| %>
  <div class="form-group">
    <%= f.hidden_field :post_id, value: @post.id %>
  </div>
  
  <div class="form-group", id="content">
    <%= f.label :comment %>
    <%= f.text_area :message, class: 'form-control', placeholder: 'Add comment' %>
  </div>

  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/home/about.html.erb
<main role="main">
  <section class="contact pt-4 pb-5">
    <div class="container">
      <h3>Wellcome to my BlogIT</h3>
      <address>
        <strong>Vladimir, Inc.</strong><br>
        103 Heroev Dnepra Streat<br>
        Kiev, Ukraive<br>
        <abbr title="Phone">P:</abbr> (096) 131-91-91
      </address>

      <address>
        <strong>Full Name</strong><br>
        <a href="mailto:#">vladimir.last@gmail.com</a>
      </address>
      <div id="map" style="height:300px;"></div>
    </div>
  </section>
</main>

app/views/home/index.html.erb
<main role="main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 content-area">

        <h3 class="entry-title">
          LIST OF POSTS:
          <small class="text-muted">The latest</small>
        </h3>

        <% if @posts.present? %>
          <% @posts.each.with_index(1) do |post, index| %>
            <ul class="list-unstyled">
              <li id="index" class="media">
                <% if post.file.attached? %>
                  <div class="mr-3" alt="Generic placeholder image">
                    <%= image_tag post.file.variant(resize: "64x64") %>
                  </div>
                <% end %>
                <div class="media-body">
                  <h5 class="mt-0"><%= link_to(post.title, post_path(post.id)) %> <span class="badge badge-secondary">New</span> <span class="badge badge-primary badge-pill"><%= post.comments.size %></span></h5>
                  <h6 class="autor">
                    Author: <%= post.user&.nickname %> | Date of creation: <%= post.created_at.to_date %>
                  </h6> 
                  <h4><%= truncate(post.content) %></h4>
                </div>
              </li>
            </ul>
          <% end %>
        <% end %>

      </div>

      <div class="col-md-4 sidebar">
        <% if current_user && current_user.posts? %>
          <h2>My list of posts:</h2>

          <% @my_posts.each.with_index(1) do |my_post, index| %>
            <aside id="index" class="widget widget-text">
              <h3 class="widget-title"><%= index %>) <%= link_to(my_post.title, post_path(my_post.id)) %></h3>
              <% if my_post.file.attached? %>
                <div class="mr-3" alt="Generic placeholder image">
                  <%= image_tag my_post.file.variant(resize: "300x250") %>
                </div>
              <% end %>
            </aside>
          <% end %>

        <% end %>
      </div>

    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker-standalone.min.css" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="bg-light">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">BlogIT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Create Post', new_post_path, :class => 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'About us', about_path , :class => 'nav-link'%></li>   
          </ul>
        </div>
        <div>
          <% if current_user %>
            <%= current_user.nickname %> |
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, method: :new %> |
            <%= link_to "Sign Up", new_user_registration_path, method: :get %>
          <% end %>
        </div>
      </nav>
    </header>

    <% if flash[:error] %>
      <p class="alert alert-primary" role="alert"><%= flash[:error] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<main role="main">
  <section class="visits pt-4 pb-4">
    <div class="container">
    <%= form_for :post, url: post_path(@post), method: :put do |f| %>
      <% if @post %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= f.label :change_title %><br />
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :change_content %><br />
        <%= f.text_area :content, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :file %>
        <%= f.file_field :file, class: 'form-control-file' %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>

    <%= link_to 'Back to list', root_path %>
    </div>
  </section>
</main>

app/views/posts/new.html.erb
<main role="main">
  <section class="visits pt-4 pb-4">
    <div class="container">
      <h1>Create new post:</h1>
      <%= form_for :post, url: posts_path do |f| %>

        <div class="form-group">
          <%= f.label :post_title %>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Add title' %>
        </div>

        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_field :content, class: 'form-control', placeholder: 'Add content' %>
        </div>

        <div class="form-group">
          <%= f.label :file %>
          <%= f.file_field :file, class: 'form-control-file' %>
        </div>
        
        <%= f.submit  :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </section>
</main>

app/views/posts/show.html.erb
<main role="main">
  <div class="pt-4 pb-4">
    <div class="container">
      <div class="col-md-12 content-area">
        <header class="entry-header">
          <h1 class="entry-title">
            <%= @post.title %>
          </h1>
          <div class="entry-meta">
            <span class="posted-on">
              <%= "Posted #{@post.created_at.to_date} by " %> <%= @post.user.nickname %> |
            </span>
            <span class="count-comments">
              Has <%= @post.comments.size %> comments
            </span>
          </div>
        </header>
        <div class="card-body">
          <p class="card-text"><%= @post.content %></p>
          <% if @post.file.attached? %>
            <div class="d-block w-100" align='center'>
              <%= image_tag @post.file.variant(resize: "720x440") %>
            </div>
          <% end %>
        </div>

        <%if can? :manage, @post %>
          <div style="padding: 5px">
            <button type="button" class="btn btn-light"><%= link_to 'Edit Post', edit_post_path(@post.id) %></button>
            <button type="button" class="btn btn-light"><%= link_to 'Delete Post', post_path(@post.id), method: :delete, data: { confirm: 'A you sure?' } %></button>
          </div>
        <% end %>

      </div>

      <% if @comments.present? %>
        <div class="container">
          <h5 class="comments-block">Comments:</h5>
          <div id="comments">
            <%= render @comments %>
          </div>
        </div>
      <% end %>

      <h5 class="add-comment">Add your comment:</h5>

      <%= render "comments/new", { comment: @comment} %>
    </div>
  </div>
</main>